Add files via upload
I tried uploading via the terminal and I tried everything I could think of. I need help with this, but I uploaded what I had for now.
chrisgehrke@Chriss-MacBook-Pro MSSE 663 % git push origin master
To https://github.com/ChrisGehrke/MSSE663-js-exercices.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://github.com/ChrisGehrke/MSSE663-js-exercices.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
chrisgehrke@Chriss-MacBook-Pro MSSE 663 % git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master